# Generated by Django 5.0.7 on 2025-04-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resfinal", "0002_alter_otptoken_otp_code_order_orderitem_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestap", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="e934f8", max_length=6),
        ),
    ]
