# Generated by Django 5.0.7 on 2025-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resfinal", "0003_location_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="b6400e", max_length=6),
        ),
    ]
