# Generated by Django 5.0.7 on 2025-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resfinal", "0004_devicelocation_delete_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevicePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("x_position", models.FloatField(default=0)),
                ("y_position", models.FloatField(default=0)),
                ("z_position", models.FloatField(default=0)),
                ("alpha", models.FloatField(default=0)),
                ("beta", models.FloatField(default=0)),
                ("gamma", models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="DeviceLocation",
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="2a5ad1", max_length=6),
        ),
    ]
