# Generated by Django 5.0.7 on 2025-04-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resfinal", "0005_deviceposition_delete_devicelocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="8e2e68", max_length=6),
        ),
    ]
