# Generated by Django 5.0.7 on 2025-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resfinal", "0006_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DevicePosition",
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="afd0fb", max_length=6),
        ),
    ]
