# Generated by Django 5.0.7 on 2025-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resfinal", "0008_alter_otptoken_otp_code_devicelocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="9d9eed", max_length=6),
        ),
    ]
